version: '3.8'

services:
  # db:
  #   image: mysql:8.0.33
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: mydatabase
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - db_data:/var/lib/mysql

  app:
    image: maven:3.8.1-openjdk-11
    working_dir: /app
    volumes:
      - .:/app
    command: mvn clean compile exec:java
    # depends_on:
    #   - db
# volumes:
#   db_data:
